# spring:
#   application:
#     name:Config-Dev

eureka:

  instance:
    hostname: localhost
    ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
  
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
